### ISSUE TITLE
Conteúdo, na versão mobile, deveria ficar fixo ao acessar o menu

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/siai-ifms-na#14]
Ao entrar na versão mobile, o conteúdo, ao acessar o menu, deveria ficar fixo e não se mover. Ou seja, ao utilizar o scroll para acessar os itens do menu na parte inferior,  o conteúdo deveria se manter no mesmo local, impedindo que o menu fiquei escondido na parte superior. 

![captura de tela 2018-10-15 as 20 58 14](https://user-images.githubusercontent.com/1373275/46986426-52b83380-d0bd-11e8-9cf4-e156d18ee8fb.png)

**Comment by gabrielmedina** [comment]
Massa! Realmente essa UX precisa funcionar conforme você descreveu nesta issue. É natural que o usuário espere que o scroll do menu flua, logo após ter aberto o mesmo.

Podemos trabalhar com um pouco de JS, escutando o evento de click do botão que abre o menu, para adicionarmos uma class no elemento pai e atacar com CSS para retirar o scroll da página, deixando somente para o menu.

Vou trabalhar nisso! 💪

**Comment by gabrielmedina** [comment]
Criei um PR #23 com uma possível solução para essa Issue 🍺 

Você pode ver o resultado aqui: [GIF](https://i.gyazo.com/d42ecbc405feed7d0e222f62695f3196.mp4) ;)

**Comment by luizpicolo** [comment]
Lindeza de mais...
