### ISSUE TITLE
Inputs ocupando muito espaço na versão mobile

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/siai-ifms-na#15]
Alguns inputs, devido ao valor muito extenso em seu conteúdo, acaba ficando desproporcional na versão mobile.

![captura de tela 2018-10-15 as 21 06 27](https://user-images.githubusercontent.com/1373275/46986614-57c9b280-d0be-11e8-9eef-cf79371803af.png)

**Comment by gabrielmedina** [comment]
Podemos corrigir isso definindo uma largura máxima para nossos `fields`, ou até mesmo forçar para que todos possuam 100% da largura do content nos dispositivos móveis.

Vou trabalhar nisso! 💪

**Comment by luizpicolo** [comment]
Que todos pudessem ficar 100% no mobile seria bem interessante. Na versão desktop a disposição também não é muito agradável.

**Comment by gabrielmedina** [comment]
Mestre, no seed básico que o projeto possui, não consigo avançar até uma tela que contenha campos de input. Consegue me dar um norte?

**Comment by luizpicolo** [comment]
Realmente no sistemas não há a possibilidade de gerar dados de exemplo para testes. Por este motivo, criei o código abaixo para adicionar dados no sistemas.

### Passo a passo 

Rode o comando

```
rails db:schema:load && rails db:seed
```

Depois, acesso o `rails console` e execute os comandos abaixo

```ruby
(1..10).each do |x|
  Course.create(name: "NomeDoCurso #{x}", initial: "NDC #{x}")
end
```

```ruby
(1..10).each do |x|
  SchoolGroup.create(name: "Turma #{x}", identifier: "Turma #{x}")
end
```

```ruby
(1..100).each do |x|
  Student.create(name: "NomeDoEstudante #{x}", course: Course.last, ra: 123, password: '12345678', password_confirmation: '12345678')
end
```

Logo após o sistemas terá dados para que os testes visuais sejam executados.

**Comment by gabrielmedina** [comment]
Nice! Farei isso para buscar uma solução ;)
