### ISSUE TITLE
Largura na versão mobile

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/siai-ifms-na#16]
O sistemas, em sua versão mobile, possui um pequeno erro em sua proporção horizontal que atrapalha na navegação. 

![captura de tela 2018-10-15 as 21 13 05](https://user-images.githubusercontent.com/1373275/46986805-3e753600-d0bf-11e8-9c47-57cdaf81429d.png)

**Comment by AraanBranco** [comment]
@luizpicolo estou tentando iniciar seu projeto, mas o docker faz um gitpull num projeto seu que não existe... pode verificar? ele faz um fetching em um projeto chamado `regressor`

**Comment by thomasgroch** [comment]
> @AraanBranco estou tentando iniciar seu projeto, mas o docker faz um gitpull num projeto seu que não existe... pode verificar? ele faz um fetching em um projeto chamado `regressor`

esse problema está resolvido aqui https://github.com/luizpicolo/siai/pull/17#issue-223105354

> @luizpicolo 

estou na página certa?
![Sistema de Apoio interno](http://tinyimg.io/i/gFHk03z.png)

**Comment by luizpicolo** [comment]
Realmente, o regressor, por causa de algumas mudanças que eu havia feito na gem e que não haviam sido commitadas, tive que por o Path para um repositório criado no meu perfil. Contudo, agora as mudanças foram aceitas pelo criador do regressor.

**Comment by luizpicolo** [comment]
Estarei verificando este commit.

**Comment by luizpicolo** [comment]
@thomasgroch sim. Na imagem você pode perceber que há um espaço em branco na lateral.

**Comment by AraanBranco** [comment]
@luizpicolo assim que olhar o PR dele me avisa, que posso ajudar com outras PR também =)

**Comment by luizpicolo** [comment]
@AraanBranco revisei e esta tudo okay. O PR #17  não resolveu o problema desta Issue ainda, mas foram mudanças satisfatórias.

**Comment by AraanBranco** [comment]
Acho que resolve dessa forma, certo?

![screenshot from 2018-10-18 13-17-03](https://user-images.githubusercontent.com/976835/47168821-45c35c00-d2d8-11e8-8d27-3f6abc8aee96.png)

**Comment by luizpicolo** [comment]
Vou analisar.

**Comment by luizpicolo** [comment]
@AraanBranco seria interessante não mudar o CSS diretamente no Bulma, pois, caso ele seja atualizado (e isso normalmente acontece) as modificações serão perdidas. Recomendo que você modifique o que necessita diretamente na pasta assets.

**Comment by AraanBranco** [comment]
beleza, vou fazer aqui!

**Comment by AraanBranco** [comment]
@luizpicolo eu olhei aqui e coloquei o reset do [Meyer](https://meyerweb.com/eric/tools/css/reset/), também tirei a duplicidade de imports que tinha, estava analizando em outros devises e parece que teria que repensar caso você for focar em mobile =)

**Comment by luizpicolo** [comment]
Eu estava checando. O foco não é mobile, mas mobile é algo que não pode faltar em nenhum projeto 😄 .  

Tente fazer _commmits_ separados para coisas distintas. Neste sentido fica mais organizado e podemos ir progredindo de forma mais "funilada".

**Comment by AraanBranco** [comment]
ah beleza, quer que tire algo ou ta okay la?

**Comment by luizpicolo** [comment]
No commit há algumas observações. Da uma checada.

**Comment by AraanBranco** [comment]
ve se era aquilo =)

**Comment by luizpicolo** [comment]
As linhas que comentei ainda não foram solucionadas. Veja

https://github.com/luizpicolo/siai/pull/18/files#diff-ef5c4c96f010f7705bdafdb6f463cdadR26

https://github.com/luizpicolo/siai/pull/18/files#diff-8b5988839f417431756d806981020df7R28

**Comment by AraanBranco** [comment]
Desculpe como n vi nenhum comentário nas linhas do PR n tinha percebido, ve se ficou bom e se precisa de mais algum ajuste =)

**Comment by luizpicolo** [comment]
Merge #18. Mas como havia falado antes, o PR #18 não resolveu esta issue

**Comment by gabrielmedina** [comment]
Amigos, aparentemente o problema do estouro da largura está sendo causado por conta dos elementos que possuem a class `columns`.

Podemos resolver esse bug, ocasionado pela técnica escolhida, ocultando o estouro no elemento `body`.

Vou enviar uma solução para discutirmos melhor.
