### ISSUE TITLE
Remover Scroll 

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/siai-ifms-na#19]
Há um _Scroll_ muito chato aparecendo ao lado do nome e email. 😄 

![capturar](https://user-images.githubusercontent.com/1373275/47398340-bb2c9380-d701-11e8-815a-7e1626aeadec.PNG)

**Comment by marataziat** [comment]
Assign to me pls :3

**Comment by fernandomaia** [comment]
@luizpicolo Posso pegar essa issue?

**Comment by luizpicolo** [comment]
Com certeza 🎉
